version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - .:/app

  frontend:
    build:
      context: ./weather-dashboard-ui
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Change the host port to avoid conflicts
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./weather-dashboard-ui:/app
