version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - .:/app
      - weather-db:/app/weather.db

  frontend:
    build:
      context: ./weather-dashboard-ui
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Change the host port to avoid conflicts
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./weather-dashboard-ui:/app

  notification:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SMTP_SERVER=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@example.com
      - SMTP_PASSWORD=your-password
      - BACKEND_URL=http://backend:8000

volumes:
  weather-db:
